title: Configuration
data:
  copyright_since: 2020
  404_title: 'Sorry we couldnt find this page.'
  404_text: 'But dont worry, you can find plenty of other things on our homepage.'
  image: images.png
